package com.zahri.lighttodo.ui.edit

import com.zahri.lighttodo.test.sourceFile

import org.junit.Assert.assertFalse
import org.junit.Assert.assertTrue
import org.junit.Test

class WheelPickerMotionSourceTest {
    @Test
    fun wheelPickerUsesCentralAppMotionForItemAlpha() {
        val source = sourceFile("app/src/main/java/com/zahri/lighttodo/ui/edit/WheelPicker.kt").readText()
        val dateTimeSource = sourceFile("app/src/main/java/com/zahri/lighttodo/ui/edit/EditDateTimePicker.kt").readText()
        val componentSource = sourceFile("app/src/main/java/com/zahri/lighttodo/ui/motion/components/WheelPickerItemMotion.kt").readText()
        val policySource = sourceFile("app/src/main/java/com/zahri/lighttodo/ui/motion/WheelPickerMotionPolicy.kt").readText()

        assertFalse(source.contains("import com.zahri.lighttodo.ui.motion.AppMotion"))
        assertTrue(source.contains("import com.zahri.lighttodo.ui.motion.WheelPickerMotionPolicy"))
        assertTrue(source.contains("import com.zahri.lighttodo.ui.motion.components.rememberWheelPickerItemMotion"))
        assertTrue(source.contains("WheelPickerMotionPolicy.proximityRadiusPx(itemHeight.toPx())"))
        assertTrue(source.contains("WheelPickerMotionPolicy.proximityForDistance"))
        assertTrue(source.contains("val itemMotion = rememberWheelPickerItemMotion(proximity)"))
        assertTrue(source.contains("textMotion: WheelPickerTextMotion = WheelPickerMotionPolicy.TimeColumnTextMotion"))
        assertTrue(source.contains("WheelPickerMotionPolicy.fontSizeForProximity(textMotion, proximity)"))
        assertTrue(source.contains("WheelPickerMotionPolicy.colorForProximity("))
        assertTrue(source.contains("WheelPickerMotionPolicy.fontWeightForProximity(proximity)"))
        assertFalse(source.contains("val fontSize = if (isSelected)"))
        assertFalse(source.contains("val color = if (isSelected)"))
        assertFalse(source.contains("val weight = if (isSelected)"))
        assertFalse(source.contains("selectedFontSize: TextUnit ="))
        assertFalse(source.contains("unselectedFontSize: TextUnit ="))
        assertTrue(source.contains("import com.zahri.lighttodo.ui.motion.components.motionWheelPickerItemLayer"))
        assertTrue(source.contains(".motionWheelPickerItemLayer(itemMotion)"))
        assertFalse(source.contains("this.alpha = itemMotion.alpha"))
        assertFalse(source.contains("scaleX = itemMotion.scale"))
        assertFalse(source.contains("scaleY = itemMotion.scale"))
        assertFalse(source.contains("import androidx.compose.ui.graphics.graphicsLayer"))
        assertFalse(source.contains("import androidx.compose.animation.core.animateFloatAsState"))
        assertFalse(source.contains("WheelPickerMotionPolicy.scaleForProximity"))
        assertFalse(source.contains("WheelPickerMotionPolicy.alphaForProximity"))
        assertFalse(source.contains("AppMotion.PickerItemAlphaMillis"))
        assertFalse(source.contains("import androidx.compose.animation.core.Animatable"))
        assertFalse(source.contains("package com.zahri.lighttodo.ui.edit\n\nobject WheelPickerMotionPolicy"))
        assertFalse(source.contains("tween(durationMillis = 150)"))
        assertFalse(source.contains("val targetAlpha = if (isSelected) 1f else 0.4f"))
        assertTrue(componentSource.contains("animateFloatAsState"))
        assertTrue(componentSource.contains("fun Modifier.motionWheelPickerItemLayer("))
        assertTrue(componentSource.contains("graphicsLayer"))
        assertTrue(componentSource.contains("alpha = itemMotion.alpha"))
        assertTrue(componentSource.contains("scaleX = itemMotion.scale"))
        assertTrue(componentSource.contains("scaleY = itemMotion.scale"))
        assertTrue(componentSource.contains("WheelPickerMotionPolicy.alphaForProximity"))
        assertTrue(componentSource.contains("WheelPickerMotionPolicy.scaleForProximity"))
        assertTrue(componentSource.contains("AppMotion.PickerItemAlphaMillis"))
        assertTrue(componentSource.contains("AppMotion.PickerItemScaleMillis"))
        assertTrue(policySource.contains("data class WheelPickerTextMotion("))
        assertTrue(policySource.contains("val DateColumnTextMotion = WheelPickerTextMotion("))
        assertTrue(policySource.contains("val TimeColumnTextMotion = WheelPickerTextMotion("))
        assertTrue(policySource.contains("val DayColumnTextMotion = WheelPickerTextMotion("))
        assertTrue(policySource.contains("const val CenterScaleBoost = 0.28f"))
        assertTrue(policySource.contains("const val FarItemAlpha = 0.42f"))
        assertTrue(policySource.contains("const val CenterItemAlpha = 1f"))
        assertTrue(policySource.contains("fun fontSizeForProximity("))
        assertTrue(policySource.contains("fun colorForProximity("))
        assertTrue(policySource.contains("fun fontWeightForProximity("))
        assertTrue(policySource.contains("fun proximityRadiusPx(itemHeightPx: Float): Float"))
        assertTrue(policySource.contains("itemHeightPx * AppMotion.PickerItemProximityRadiusItems"))
        assertTrue(dateTimeSource.contains("import com.zahri.lighttodo.ui.motion.WheelPickerMotionPolicy"))
        assertTrue(dateTimeSource.contains("textMotion = WheelPickerMotionPolicy.DateColumnTextMotion"))
        assertTrue(dateTimeSource.contains("textMotion = WheelPickerMotionPolicy.TimeColumnTextMotion"))
        assertTrue(dateTimeSource.contains("textMotion = WheelPickerMotionPolicy.DayColumnTextMotion"))
        assertFalse(dateTimeSource.contains("selectedFontSize ="))
        assertFalse(dateTimeSource.contains("unselectedFontSize ="))
    }
}
